# Generated by Django 3.0.5 on 2020-06-03 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200530_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_status_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.OrderStatus'),
        ),
    ]
